load("@hermetic_cc_toolchain//toolchain:defs.bzl", zig_toolchains = "toolchains")

zig_toolchains()

# Instead of adding the toolchains to .bazelrc, they can be added unconditionally like this:
# register_toolchains(
#     "@zig_sdk//toolchain:linux_amd64_gnu.2.28",
#     "@zig_sdk//toolchain:linux_arm64_gnu.2.28",
#     "@zig_sdk//toolchain:darwin_amd64",
#     "@zig_sdk//toolchain:darwin_arm64",
#     "@zig_sdk//toolchain:windows_amd64",
#     "@zig_sdk//toolchain:windows_arm64",
#     "@zig_sdk//toolchain:wasip1_wasm",
# )
#
# And append this to .bazelrc:
# build --action_env BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 
